---
#---------------- Chaincode Deployment ---------------------
apiVersion: apps/v1 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: chaincode-basic-org2
  labels:
    app: chaincode-basic-org2
spec:
  selector:
    matchLabels:
      app: chaincode-basic-org2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: chaincode-basic-org2
    spec:
      containers:
        - image: raymanan/basic-cc-hlf:8.0
          name: chaincode-basic-org2
          imagePullPolicy: Always
          env:
            - name: CHAINCODE_ID
              value: "basic:835233e545cc337929917cd0819fed89bcc900410c0fb13859f754705bd0aff4"
            - name: CHAINCODE_SERVER_ADDRESS
              value: "0.0.0.0:7052"
          ports:
            - containerPort: 7052
